formatter: "markdown table" # this is required

sections:
  hide: []
  show:
    - requirements
    - providers
    - inputs
    - outputs
    - resources

content: |-
  ## Requirements

  | Name | Version |
  |------|---------|
  {{- range .Module.Requirements }}
  | `{{ .Name }}` | {{ .Version }} |
  {{- end }}

  ## Providers

  | Name | Version | Reference |
  |------|---------|-----------|
  {{- range .Module.Providers }}
  | `{{ .Name }}` | {{ .Version }} | [{{ .Position.Filename }}]() |
  {{- end }}

  {{ .Inputs }}

  {{ .Outputs }}

  ## Resources
  {{ range .Module.Resources }}
  * [`{{ .Mode }}.{{ .ProviderName }}_{{ .Type }}`](https://registry.terraform.io/providers/{{ .ProviderSource }}/latest/docs/{{ if eq .Mode "data" }}data-sources{{ end }}/{{ .Type }})
  {{- end }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

settings:
  anchor: false
  default: true
  escape: false
  hide-empty: false
  html: false
  indent: 2
  lockfile: false
  read-comments: false
  required: true
  sensitive: true
  type: true
