---
# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

name: Run Markdownlint
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Run Markdownlint
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2.10.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            registry.npmjs.org:443

      - name: Checkout Source
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          ref: main

      - name: Install Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "20"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Markdownlint
        run: |
          npm exec -y -- \
            markdownlint-cli@0.39.0 \
              --ignore=node_modules \
              --ignore=.github \
              --ignore=.templates \
              --fix \
              '**/*.md'

      - name: Git commit if changed
        run: |
          git config user.name "Northwood Labs (Bot)"
          git config user.email "bot@northwood-labs.com"

          set +e

          git add .
          git status | grep modified
          if [ $? -eq 0 ]; then
            git commit -a -m "automation: Updated AUTHORS and CHANGELOG on $(date)."
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git main
          fi
